CREATE DATABASE As2_Bindu;
USE As2_Bindu;
CREATE TABLE PRODUCTDETAILS(
  ProductNo VARCHAR(5) PRIMARY KEY,
  ProductName VARCHAR(25) NOT NULL,
  ProductType VARCHAR(25) NOT NULL,
  Manufacturer VARCHAR(25) NOT NULL,
  Price DECIMAL(10,2) NOT NULL,
  Weight DECIMAL(5,2) NOT NULL
);


select * from  PRODUCTDETAILS;